site_name: OpenVNet
site_favicon: favicon.png
site_description: Documentation for OpenVNet

theme: readthedocs
docs_dir: content
use_directory_urls: true

repo_url: https://github.com/axsh/openvnet

copyright: Copyright &copy; 2015, <a href="http://axsh.jp/">Axsh Co. Ltd.</a>.
google_analytics: ['UA-63388719-2', 'auto']

pages:
- Home: 'index.md'
#- 'Concept': 'concept.md'
- Installation : 'installation.md'
- Creating virtual networks:
  - 'Single network': 'creating-virtual-networks/single-network.md'
  - 'Single network with DHCP server': 'creating-virtual-networks/single-network-dhcp.md'
  - 'Two networks': 'creating-virtual-networks/two-networks.md'
  - 'Two network with router': 'creating-virtual-networks/two-networks-router.md'
- Configuration files:
  - 'common.conf': 'configuration-files/common.md'
  - 'vnmgr.conf': 'configuration-files/vnmgr.md'
  - 'webapi.conf': 'configuration-files/webapi.md'
  - 'vna.conf': 'configuration-files/vna.md'
  - 'vnctl.conf': 'configuration-files/vnctl.md'
- Vnctl:
  - 'datapaths' : 'vnctl/datapaths.md'
  - 'interfaces': 'vnctl/interfaces.md'
  - 'networks'  : 'vnctl/networks.md'
- Debugging:
  - 'vnflows-monitor': 'debugging/vnflows-monitor.md'
  - 'troubleshooting': 'debugging/troubleshooting.md'
- Community: 'community.md'
