site_name: OpenVNet
site_favicon: favicon.png
site_description: Documentation for OpenVNet

theme: readthedocs
docs_dir: content
use_directory_urls: true

repo_url: https://github.com/axsh/openvnet

copyright: Copyright &copy; 2015, <a href="http://axsh.jp/">Axsh Co. Ltd.</a>.
google_analytics: ['UA-63388719-2', 'auto']

pages:
- 'Home': 'index.md'
#- 'Concept': 'concept.md'
- Getting Started:
  - 'Installation': 'installation.md'
  - 'Single network with DHCP server': 'single-network-dhcp.md'
- Support:
  - 'Community': 'community.md'

